---

- name: Instalar stack LEMP en localhost con Ansible (Centos 7)
  hosts: localhost
  become: true


  tasks:
  - name: Instalar repositorio epel-release
    yum:
      name: epel-release
      state: present

  - name: Instalar NGINX
    yum:
      name: nginx
      state: present

  - name: Habilitar NGINX
    systemd:
      name: nginx
      enabled: yes

  - name: Startear NGINX
    service:
      name: nginx
      state: started

  - name: Instalar MARIADB-SERVER
    yum:
      name: mariadb-server
      state: present

  - name: Startear MARIADB
    service:
      name: mariadb
      state: started

  - name: Habilitar MARIADB
    systemd:
      name: mariadb
      enabled: yes

  - name: Instalar PHP
    yum:
      name: php
      state: present

  - name: Instalar PHP-MYSQL
    yum:
      name: php-mysql
      state: present

  - name: Instalar PHP-FPM
    yum:
      name: php-fpm
      state: present

  - name: Configurar php.ini
    ini_file:
      path: /etc/php.ini
      section: PHP
      option: cgi.fix_pathinfo
      value: 0

  - name: Configurar www.conf
    ini_file:
      path: /etc/php-php.d/www.conf
      section: www
      option: listen
      value: /var/run/php-fpm/php-fpm.sock
    
  - ini_file:
      path: /etc/php-php.d/www.conf
      section: www
      option: listen.owner
      value: nobody

  - ini_file:
      path: /etc/php-php.d/www.conf
      section: www
      option: listen.group
      value: nobody

  - ini_file:
      path: /etc/php-php.d/www.conf
      section: www
      option: user
      value: nginx

  - ini_file:
      path: /etc/php-php.d/www.conf
      section: www
      option: group
      value: nginx

  - name: Startear PHP-FPM
    service:
      name: php-fpm
      state: started

  - name: Habilitar PHP-FPM
    systemd:
      name: php-fpm
      enabled: yes

  - name: Copiar arhivo de configuracion de NGINX para procesar paginas PHP
    template:
      src: default.conf
      dest: /etc/nginx/conf.d/default.conf

  - name: Restartear NGINX
    service:
      name: nginx
      state: restarted

  - name: Copiar archivo info.php al web root para probar que funcione correctamente
    template:
      src: info.php
      dest: /usr/share/nginx/html/info.php



 
